import { getHeavyMetalReport } from '../actions/heavyMetalActions'

export default async function HeavyMetalRiskCard({ landId }: { landId: string }) {
  console.log('[HeavyMetalRiskCard] landId received:', landId)
  // Fetch the latest generated report for this land plot
  const report = await getHeavyMetalReport(landId)
  console.log('[HeavyMetalRiskCard] report:', report)

  if (!report) {
    // No report exists = mostly likely no abiotic scans triggered the pipeline yet.
    return (
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-4">
        <div className="text-gray-400 text-sm flex items-center gap-2">
          <span className="text-xl">🧪</span>
          <span>এই জমির জন্য কোনো ভারি ধাতু পরীক্ষার রিপোর্ট নেই। (No Heavy Metal data)</span>
        </div>
      </div>
    )
  }

  // Style according to severity
  const isCritical = report.severity === 'critical'
  const isHigh = report.severity === 'high'
  const isModerate = report.severity === 'moderate'
  
  const bgClass = isCritical ? 'bg-rose-50 border-rose-200' :
                  isHigh ? 'bg-red-50 border-red-200' :
                  isModerate ? 'bg-orange-50 border-orange-200' : 
                  'bg-green-50 border-green-200'

  const textClass = isCritical ? 'text-rose-900' :
                    isHigh ? 'text-red-800' :
                    isModerate ? 'text-orange-800' : 
                    'text-green-800'

  const scorePct = Math.round(Number(report.confidence_score) * 100)

  // Map metal type to Bengali
  const metalBnMap: Record<string, string> = {
    'chromium': 'ক্রোমিয়াম (Chromium)',
    'lead': 'সীসা (Lead)',
    'arsenic': 'আর্সেনিক (Arsenic)',
    'cadmium': 'ক্যাডমিয়াম (Cadmium)',
    'mixed': 'মিশ্র ধাতু (Mixed)',
  }
  const metalName = metalBnMap[report.metal_type] || report.metal_type

  return (
    <div className={`rounded-xl shadow-sm border p-5 ${bgClass}`}>
      <div className="flex justify-between items-start mb-4 border-b border-black/5 pb-3">
        <div>
          <h3 className={`font-bold text-lg flex items-center gap-2 ${textClass}`}>
            <span>⚠️ ভারি ধাতু দূষণ ঝুঁকি (Heavy Metal Risk)</span>
          </h3>
          <p className="text-xs text-gray-500 mt-1">
            শেষ আপডেট: {new Date(report.reported_at).toLocaleDateString('bn-BD')}
          </p>
        </div>
        <div className={`px-3 py-1 rounded-full text-xs font-black uppercase tracking-wider border
          ${isCritical ? 'bg-rose-100 text-rose-800 border-rose-300' : 
            isHigh ? 'bg-red-100 text-red-800 border-red-300' : 
            isModerate ? 'bg-orange-100 text-orange-800 border-orange-300' : 
            'bg-green-100 text-green-800 border-green-300'}
        `}>
          {report.severity}
        </div>
      </div>

      <div className="space-y-4">
        {/* Vital Stats */}
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-white/60 p-3 rounded-lg border border-white">
            <div className="text-xs text-gray-500 font-bold mb-1">সম্ভাব্য ধাতু</div>
            <div className={`text-base font-black ${textClass}`}>{metalName}</div>
          </div>
          
          <div className="bg-white/60 p-3 rounded-lg border border-white">
            <div className="text-xs text-gray-500 font-bold mb-1">ঝুঁকি স্কোর (Risk)</div>
            <div className="flex items-end gap-1">
              <span className={`text-2xl font-black leading-none ${textClass}`}>{scorePct}</span>
              <span className="text-sm font-bold text-gray-400 mb-0.5">/100</span>
            </div>
          </div>
        </div>

        {/* Notes (Generated by RPC) */}
        {report.notes && (
          <div className="bg-white/80 p-3 text-sm rounded-lg border border-black/5 text-gray-700 leading-relaxed font-medium">
            <span className="font-bold text-gray-900 block mb-1">AI বিশ্লেষণ:</span>
            {report.notes}
          </div>
        )}

        {/* Warning Box */}
        {scorePct >= 50 && (
          <div className="mt-2 text-xs bg-red-100/50 text-red-800 p-2 rounded flex gap-2">
            <span className="text-lg">🛑</span>
            <span>
              <strong>সতর্কতা:</strong> এই জমিতে উৎপাদিত ফসলে ভারি ধাতুর উপস্থিতি থাকতে পারে। 
              সরাসরি বিক্রির আগে ল্যাব টেস্ট করার পরামর্শ দেওয়া হচ্ছে।
            </span>
          </div>
        )}
      </div>
    </div>
  )
}
