'use client'

import { useMemo } from 'react'
import { useSearchParams } from 'next/navigation'

type ComplaintPayload = {
  farmerId: string
  alert: {
    event_id: string
    source_name_bn?: string | null
    source_type?: string
    severity?: string
    distance_m?: number
    alert_message_bn?: string
    factory_name_bn?: string | null
    water_color?: string | null
    fish_kill?: boolean
    farmer_count?: number
    reported_at?: string
  }
}

export default function DoeComplaintPage() {
  const searchParams = useSearchParams()
  const dataParam = searchParams.get('data')

  const payload = useMemo<ComplaintPayload | null>(() => {
    if (!dataParam) return null
    try {
      return JSON.parse(decodeURIComponent(dataParam)) as ComplaintPayload
    } catch {
      return null
    }
  }, [dataParam])

  if (!payload) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 p-6">
        <div className="bg-white border border-gray-200 rounded-2xl p-6 text-center">
          <p className="text-sm text-gray-600">অভিযোগ তথ্য পাওয়া যায়নি।</p>
        </div>
      </div>
    )
  }

  const { farmerId, alert } = payload
  const today = new Date().toLocaleDateString('bn-BD')
  const reportedAt = alert.reported_at
    ? new Date(alert.reported_at).toLocaleDateString('bn-BD')
    : '—'
  const distanceKm = alert.distance_m != null ? (alert.distance_m / 1000).toFixed(1) : '—'

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <style>{`
        @media print {
          .no-print { display: none; }
          body { background: white; }
        }
      `}</style>

      <div className="max-w-3xl mx-auto bg-white border border-gray-200 rounded-2xl p-6">
        <div className="flex items-start justify-between gap-3">
          <div>
            <h1 className="text-lg font-bold text-gray-900">দূষণ অভিযোগ (DoE)</h1>
            <p className="text-xs text-gray-500 mt-1">তারিখ: {today}</p>
          </div>
          <button
            className="no-print px-3 py-1.5 text-xs font-semibold bg-green-600 text-white rounded-lg hover:bg-green-700"
            onClick={() => window.print()}
          >
            🧾 প্রিন্ট/পিডিএফ
          </button>
        </div>

        <div className="mt-5 text-sm text-gray-700 leading-relaxed space-y-3">
          <p>
            প্রাপক: পরিবেশ অধিদপ্তর (DoE)
          </p>
          <p>
            বিষয়: কৃষিজমির নিকটবর্তী পানির দূষণ সংক্রান্ত অভিযোগ।
          </p>
          <p>
            সম্মানিত মহোদয়,<br />
            আমাদের এলাকায় পানির দূষণের ঘটনা চিহ্নিত হয়েছে। নিচের তথ্যের ভিত্তিতে দ্রুত ব্যবস্থা গ্রহণের অনুরোধ করছি।
          </p>
        </div>

        <div className="mt-4 border border-gray-100 rounded-xl p-4">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">ঘটনার বিবরণ</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-gray-600">
            <div><span className="text-gray-400">ইভেন্ট আইডি:</span> {alert.event_id}</div>
            <div><span className="text-gray-400">রিপোর্ট তারিখ:</span> {reportedAt}</div>
            <div><span className="text-gray-400">উৎস:</span> {alert.source_name_bn ?? 'অজানা উৎস'}</div>
            <div><span className="text-gray-400">ধরণ:</span> {alert.source_type ?? '—'}</div>
            <div><span className="text-gray-400">তীব্রতা:</span> {alert.severity ?? '—'}</div>
            <div><span className="text-gray-400">দূরত্ব:</span> {distanceKm} কিমি</div>
            <div><span className="text-gray-400">সম্ভাব্য কারখানা:</span> {alert.factory_name_bn ?? '—'}</div>
            <div><span className="text-gray-400">পানির রঙ:</span> {alert.water_color ?? '—'}</div>
            <div><span className="text-gray-400">মরা মাছ:</span> {alert.fish_kill ? 'হ্যাঁ' : 'না'}</div>
            <div><span className="text-gray-400">রিপোর্টকারী কৃষক:</span> {alert.farmer_count ?? 0} জন</div>
          </div>
          {alert.alert_message_bn && (
            <p className="text-xs text-gray-600 mt-3">
              <span className="text-gray-400">বার্তা:</span> {alert.alert_message_bn}
            </p>
          )}
        </div>

        <div className="mt-5 text-sm text-gray-700 leading-relaxed space-y-3">
          <p>
            দয়া করে দ্রুত তদন্ত ও প্রয়োজনীয় ব্যবস্থা গ্রহণ করুন। কৃষকের ফসল ও জনস্বাস্থ্যের সুরক্ষার স্বার্থে
            এই অভিযোগটি অগ্রাধিকার ভিত্তিতে দেখা প্রয়োজন।
          </p>
          <p>
            আবেদনকারী (Farmer ID): <span className="font-mono text-xs">{farmerId}</span>
          </p>
        </div>

        <div className="mt-8 text-xs text-gray-400">
          Generated by AgroSentinel • Reference only
        </div>
      </div>
    </div>
  )
}
